name: CI
on:
    push:
        branches: [main]
        tags:
            - "*-v*"
    pull_request:

env:
    CMAKE_CXX_COMPILER_LAUNCHER: ccache
    CC: /usr/src/clang-p2996/build/bin/clang
    CXX: /usr/src/clang-p2996/build/bin/clang++

jobs:
    build:
        name: matt-daemon-clang-p2996-${{ matrix.build_type }}
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/jakobus42/clang-p2996-dev:latest
        strategy:
            matrix:
                # somehow tsan and asan dont work because linker cant find libclang_rt.tsan_cxx.a
                # and libclang_rt.asan_cxx.a.
                # this would have to be fixed in ghcr.io/jakobus42/clang-p2996-dev:latest
                build_type: [debug, analyze, release]
        steps:
            - uses: actions/checkout@v4

            - name: Setup ccache
              uses: hendrikmuhs/ccache-action@v1.2
              with:
                  key: clang-p2996-${{ matrix.build_type }}
                  create-symlink: true
                  update-package-index: true

            - name: Build
              run: |
                  cmake --preset ${{ matrix.build_type }}
                  cmake --build --preset ${{ matrix.build_type }}

            - name: Test
              run: ctest -C ${{ matrix.build_type }} --test-dir build/${{ matrix.build_type }}

    release:
        needs: build
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/jakobus42/clang-p2996-dev:latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            - name: Setup ccache
              uses: hendrikmuhs/ccache-action@v1.2
              with:
                  create-symlink: true
                  update-package-index: true

            - name: Build
              run: |
                  cmake --preset release
                  cmake --build --preset release
            - name: Test
              run: ctest -C release --test-dir build/release

            - name: Get component
              id: pkg
              run: |
                  TAG="${GITHUB_REF#refs/tags/}"
                  echo "component=${TAG%-v*}" >> $GITHUB_OUTPUT
                  echo "version=${TAG#*-v}" >> $GITHUB_OUTPUT

            - name: CPack
              working-directory: build/release
              run: cpack -D CPACK_COMPONENTS_ALL=${{ steps.pkg.outputs.component }}

            - name: Publish
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      build/release/*.deb
                      build/release/*.tar.gz
                  tag_name: ${{ github.ref_name }}
                  name: ${{ steps.pkg.outputs.component }}-${{ steps.pkg.outputs.version }}
