name: Doc
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy-doc
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jakobus42/clang-p2996-dev:latest
    permissions:
      pages: write
      id-token: write
    environment: github-pages
    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen
        run: |
          apt-get update
          apt-get install -y doxygen graphviz pip

      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install Sphinx
        run: pip install -r doc/requirements.txt

      - name: Build Doc
        run: |
          cmake --preset doc
          cmake --build --preset doc

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/build/html

      - name: Deploy
        uses: actions/deploy-pages@v4
