name: request-clang-format

on:
  issue_comment:
    types: [ created ]

jobs:
  format:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, 'run-format') && (github.actor == 'ifaoji' || github.actor == 'Jakobus42')
    runs-on: ubuntu-latest
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v3
        id: pr-branch

      - uses: actions/checkout@v6
        with:
          ref: ${{ steps.pr-branch.outputs.head_ref }}
    
      - name: Run clang format
        uses: DoozyX/clang-format-lint-action@v0.20
        with:
            source: "."
            extensions: "c,h,cpp,hpp,tpp"
            clangFormatVersion: 20
            inplace: True

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
            author_name: clang-format[bot]
            author_email: github-actions[bot]@users.noreply.github.com

      - name: React to comment
        uses: dkershner6/reaction-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reaction: "eyes"
